### ISSUE TITLE
Switch data model to the new simonsobs/soapack library

### ISSUE THREAD

**Issue by msyriac** [ACTCollaboration/tile-c#16]
https://github.com/simonsobs/soapack

**Comment by kaizokuow** [comment]
Is soapack package removed ?
I'm very interested in "The Atacama Cosmology Telescope: Component-separated maps of CMB temperature and the thermal Sunyaev-Zel'dovich effect", but the ILC code depends on soapack package.

**Comment by msyriac** [comment]
soapack has the ACT data model in it, so it's only useful if you have the raw data products from ACT, which are not yet public.
